### ISSUE TITLE
part of Scripting example doesn't work?

### ISSUE THREAD

**Issue by pmcdonal** [adematti/pypescript#3]
In /doc/user/scripting.rst, the line:
from template_lib.model import FlatModel
gives me
ModuleNotFoundError: No module named 'template_lib.model'
(was looking at the in-python form to help understand the yaml example above, then trying to run to understand that)

**Comment by adematti** [comment]
Hi,
This should be made slightly clearer in the new commit. You need to install template_lib to run this example, e.g.
`python setup.py develop`
in template_lib/ directory (as its name suggests, this a template library not really part of pypescript itself).

**Comment by pmcdonal** [comment]
I had tried this, and did again after updating, but it still doesn't find it. Does the following mean the install failed?

pmcdonal@MacBook-Pro-10 template_lib % python setup.py develop
running develop
running build_scripts
running egg_info
running build_src
build_src
building py_modules sources
building library "pypelib" sources
building library "fpypelib" sources
building extension "template_lib.module_cpp.module" sources
building extension "template_lib.module_f90.module" sources
building extension "template_lib.module_c.module" sources
building data_files sources
build_src: building npy-pkg config files
writing template_lib.egg-info/PKG-INFO
writing dependency_links to template_lib.egg-info/dependency_links.txt
writing requirements to template_lib.egg-info/requires.txt
writing top-level names to template_lib.egg-info/top_level.txt
reading manifest file 'template_lib.egg-info/SOURCES.txt'
writing manifest file 'template_lib.egg-info/SOURCES.txt'
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_clib
CCompilerOpt.__init__[765] : load cache from file -> /Users/pmcdonal/Programs/Arnaud/pypescript/template_lib/build/temp.macosx-10.9-x86_64-3.7/ccompiler_opt_cache_clib.py
CCompilerOpt.__init__[776] : hit the file cache
get_default_fcompiler: matching types: '['gnu95', 'nag', 'absoft', 'ibm', 'intel', 'gnu', 'g95', 'pg']'
customize Gnu95FCompiler
Found executable /Users/pmcdonal/opt/anaconda3/bin/x86_64-apple-darwin13.4.0-gfortran
Found executable /Users/pmcdonal/opt/anaconda3/bin/x86_64-apple-darwin13.4.0-ld
Found executable /Users/pmcdonal/opt/anaconda3/bin/x86_64-apple-darwin13.4.0-ar
Found executable /Users/pmcdonal/opt/anaconda3/bin/x86_64-apple-darwin13.4.0-ranlib
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    license='GPLv3')
  File "/Users/pmcdonal/Programs/Arnaud/pypescript/pypescript/libutils/setup.py", line 322, in __init__
    **kwargs)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/pmcdonal/Programs/Arnaud/pypescript/pypescript/libutils/setup.py", line 304, in run
    _develop.run(_self)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/setuptools/command/develop.py", line 34, in run
    self.install_for_development()
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/command/develop.py", line 15, in install_for_development
    old_develop.install_for_development(self)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/setuptools/command/develop.py", line 114, in install_for_development
    self.run_command('build_ext')
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/command/build_ext.py", line 115, in run
    build_clib.run()
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/command/build_clib.py", line 154, in run
    c_compiler=self.compiler)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py", line 879, in new_fcompiler
    c_compiler=c_compiler)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py", line 853, in get_default_fcompiler
    c_compiler=c_compiler)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py", line 800, in _find_existing_fcompiler
    c.customize(dist)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py", line 505, in customize
    get_flags('opt', oflags)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py", line 496, in get_flags
    flags.extend(getattr(self.flag_vars, tag))
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/environment.py", line 40, in __getattr__
    return self._get_var(name, conf_desc)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/environment.py", line 56, in _get_var
    var = self._hook_handler(name, hook)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py", line 703, in _environment_hook
    return hook()
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/gnu.py", line 223, in get_flags_opt
    v = self.get_version()
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/__init__.py", line 424, in get_version
    version = CCompiler.get_version(self, force=force, ok_status=ok_status)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/ccompiler.py", line 88, in <lambda>
    m = lambda self, *args, **kw: func(self, *args, **kw)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/ccompiler.py", line 653, in CCompiler_get_version
    version = matcher(output)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/gnu.py", line 272, in version_match
    v = self.gnu_version_match(version_string)
  File "/Users/pmcdonal/opt/anaconda3/lib/python3.7/site-packages/numpy/distutils/fcompiler/gnu.py", line 74, in gnu_version_match
    raise ValueError(err + version_string)
ValueError: A valid Fortran version was not found in this string:
x86_64-apple-darwin13.4.0-gfortran: warning: couldn’t understand version 11.6

9.3.0

########### CLIB COMPILER OPTIMIZATION ###########
Platform      : 
  Architecture: x64
  Compiler    : clang

CPU baseline  : 
  Requested   : 'min'
  Enabled     : SSE SSE2 SSE3
  Flags       : -msse -msse2 -msse3
  Extra checks: none

CPU dispatch  : 
  Requested   : 'max -xop -fma4'
  Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
  Generated   : none
CCompilerOpt.cache_flush[809] : write cache to path -> /Users/pmcdonal/Programs/Arnaud/pypescript/template_lib/build/temp.macosx-10.9-x86_64-3.7/ccompiler_opt_cache_clib.py
